package com.hrms.project.enums;

public enum ErrorCode {
    WORKER_NOT_FOUND,
    SITE_NOT_FOUND,
    WORKER_INACTIVE,
    SITE_INACTIVE,
    DUPLICATE_CLOCK_IN,
    OPEN_ATTENDANCE_NOT_FOUND,
    INVALID_SETTLEMENT_MONTH,
    ALREADY_SETTLED,
    INVALID_DATE_RANGE,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
